tasks:
  - name: Update Linux and Install other Chrome Dependencies
    init: |
      sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get install -y libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1
  - name: Create VirtualEnv, Install Python Dependencies
    init: |
      python -m venv env
      source env/bin/activate
      pip install -r requirements.txt
github:
  prebuilds:
    addBadge: true
vscode:
  extensions:
    - usernamehw.errorlens
    - vscode-icons-team.vscode-icons
    - bierner.markdown-preview-github-styles
    - ms-python.python
    - ms-toolsai.jupyter
    - KevinRose.vsc-python-indent
    - eamodio.gitlens
    - Gruntfuggly.todo-tree